### PR TITLE
Optimize

### PR DESCRIPTION
**Pull request by nir0s**
* Added a huge test as I don't have time for anything else right now. Even the test for colorization doesn't check for correctness, but rather for the existence of colors.
* We should finally start migrating from pytype to mypy in all projects, so... here we go.
* We should probably stop using that Makefile thing.. may just remove it before we merge this.

### CODE REVIEW

**Review by m1keil — COMMENTED** [review]
I rather not change all these variable names. I want the code to be as close as possible to the original.

**Comment by nir0s** [comment]
You mean close to the Go code?

**Comment by m1keil** [comment]
> You mean close to the Go code?

Yep. As close as possible.

**Comment by nir0s** [comment]
gg. I'll just add a pylint comment on the variable names.

**Comment by m1keil** [comment]
ehh...

**Pull request merged**
